### ISSUE TITLE
Error en el nombre de los archivos 

### ISSUE THREAD

**Issue by marioy47** [germanescobar/convertloop-php#2]
Los archivos `client.php`,  `people.php` y `convertloop.php` no se adhieren al PSR por que en versiones más recientes de PHP generan el siguiente error:

![error-convertloop](https://user-images.githubusercontent.com/3419025/43613845-a6c37858-9676-11e8-85d1-4d72cb1792ee.png)

La solución es cambiar el nombres a `Client.php`, `People.php` y `ConvertLoop.php`  respectivamente  (el nombre del archivo debe coincidir exactamente con el nombre de la clase que guarda)

**Comment by germanescobar** [comment]
Gracias Mario, lo vamos a revisar. @anayib
